#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
  path: /
  methods: GET
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: ui\home.html.twig